spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/auth/realms/globalbooks
          jwk-set-uri: http://localhost:8180/auth/realms/globalbooks/protocol/openid-connect/certs

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
